name: adora_baby
version: 1.0.8+8
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0-394.0.dev <3.7.9'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: 4.6.5
  get_cli: ^1.8.1
  floating_frosted_bottom_bar: ^0.0.1
  flutter_svg: ^1.1.6
  auto_size_text: ^3.0.0
  dio: ^4.0.6
  rxdart: ^0.27.7
  flutter_secure_storage: ^6.0.0
  lottie: ^2.0.0
  http: ^0.13.5
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  cached_network_image: ^3.2.2
  chips_choice: ^3.0.0
  carousel_slider: ^4.1.1
  shimmer: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.6.2
  share_plus: ^5.0.0
  responsive_framework: ^0.2.0
  dio_smart_retry: ^1.4.0
  dio_cache_interceptor: ^3.3.1
  pull_to_refresh: ^2.0.0
  getwidget: ^3.0.1
  flutter_switch: ^0.3.2
  flutter_launcher_icons: ^0.11.0
  pie_chart: ^5.3.2
  image_picker: ^0.8.6+1
  permission_handler: ^10.2.0
  image_cropper: ^3.0.1
  http_parser: ^4.0.2
  timelines: ^0.1.0
  firebase_core: ^2.7.0
  flutter_local_notifications: ^13.0.0
  firebase_messaging: ^14.4.0
  path_provider: ^2.0.14
  url_launcher: ^6.1.10
  flutter_widget_from_html_core: any
  infinite_scroll_pagination: ^3.2.0
  flutter_hooks: ^0.18.6


dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/loader.json



  fonts:
    - family: Playfair
      fonts:
        - asset: assets/fonts/playfair/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/playfair/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/playfair/PlayfairDisplay-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          weight: 400
          style: italic

