// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD579EfN3cU8zWeU5vrV3XRfbEe2o2BQE',
    appId: '1:205110042083:web:f9492d0065e98f6e43d4d6',
    messagingSenderId: '205110042083',
    projectId: 'adorababy-notification',
    authDomain: 'adorababy-notification.firebaseapp.com',
    storageBucket: 'adorababy-notification.appspot.com',
    measurementId: 'G-9B96E9FV58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5KPGyUMrzwAh5HohXIUkCzysXIcYNTbE',
    appId: '1:205110042083:android:b895d126aaed8e6343d4d6',
    messagingSenderId: '205110042083',
    projectId: 'adorababy-notification',
    storageBucket: 'adorababy-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB39qRKOKmAQOO53r9dMlokbXSUP5ENjno',
    appId: '1:205110042083:ios:919175e56038de2843d4d6',
    messagingSenderId: '205110042083',
    projectId: 'adorababy-notification',
    storageBucket: 'adorababy-notification.appspot.com',
    iosClientId: '205110042083-jbmevqj5h5fbs9ah8ngs8datqrgjva1s.apps.googleusercontent.com',
    iosBundleId: 'com.adorababy.adoraBaby',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB39qRKOKmAQOO53r9dMlokbXSUP5ENjno',
    appId: '1:205110042083:ios:919175e56038de2843d4d6',
    messagingSenderId: '205110042083',
    projectId: 'adorababy-notification',
    storageBucket: 'adorababy-notification.appspot.com',
    iosClientId: '205110042083-jbmevqj5h5fbs9ah8ngs8datqrgjva1s.apps.googleusercontent.com',
    iosBundleId: 'com.adorababy.adoraBaby',
  );
}
